### PR TITLE
Improved Documentation

### PR DESCRIPTION
**Pull request by UdhavKumar**

### CODE REVIEW

**Review by mvoitko — CHANGES_REQUESTED** [review]
Doesn't make any sense

**Comment by quantumpacket** [comment]
> Doesn't make any sense

This user is likely submitting this as their "hacktoberfest" PR. Many projects are going to be spammed with these useless PRs for the next 31 days.

**Comment by UdhavKumar** [comment]
Sorry Sir i am not saying to merge it but let the pull request be open or atleast dont report it i was here to help you people in documentation

**Comment by quantumpacket** [comment]
> Sorry Sir i am not saying to merge it but let the pull request be open or atleast dont report

So your only intent was to open a spam PR that would not be merged, but would be counted in hacktoberfest? Gotcha. :+1:

**Comment by faif** [comment]
@UdhavKumar Closing this for now, but please stop submitting such pull requests cause we'll report them as spam

**Pull request closed without merging**
