### PR TITLE
correct decorator pattern

### PR DESCRIPTION
**Pull request by Devroman**
Hello! You've used a decorator statement in example of decorator pattern, but it's wrong, because decorator(pattern) must be based on object-oriented programming. Decorator must be able to be added at runtime.

### CODE REVIEW

**Comment by youtux** [comment]
The decorator pattern is alredy implemented correctly, and it takes advantage of python `decorators`.
In Python, decorators can be applied to function or classes, and they are executed at runtime, since it is an interpreted language.

**Comment by Devroman** [comment]
Yes, Youtux, decorator can be implemented on class, but this example uses a functional style.
By "runtime" I understand hot-swap ability.
Can you please tell where I'm wrong?
Thanks!

**Comment by youtux** [comment]
The example uses decorators on functions because most of the time you don't actually need a class to do simple things.

Now I can see your point. You would like to be able to get an object decorated by another at runtime, while the example just modify the behaviour of the function. In that case you can just avoid using the `@decorator` syntax and call it explicitly, something like

```
wrapped_fn = decorator(original_fn)
```

**Comment by Devroman** [comment]
Oh.. Yep, You're right. :)

**Pull request closed without merging**
