### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by ashmit-coder**

### CODE REVIEW

**Comment by namelivia** [comment]
I believe this is just [spam for Hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update).
```
We’ve traced the majority of this year’s spammy contributions back to a participant with a large online audience who openly encouraged their community to take part in spammy activities, including ideas on how to game the system.
```

The [five PR's this user has opened recently](https://github.com/ashmit-coder?tab=overview&from=2020-09-01&to=2020-09-30) look very similar to [what that participant is recommending to do in order to game the system](https://www.youtube.com/watch?v=YiDjLTXXm-c&t=258s).

**Comment by ashmit-coder** [comment]
I am sorry for this but I am not under anyone's influence two of my requests were already pulled and i just want the shirt to show my parents that i dont waste 1 hour each day on the pc. I love open source too, I promise to give more effort please help me with some advice if you like sir

**Comment by ashmit-coder** [comment]
Also If  you want I can do some edits for you I am ready to learn. Also do you know how can we download pdfs from wikipedia page using python I am trying to write that code for a week but i am not getting anything, I wish you help

**Comment by faif** [comment]
"i just want the shirt to show my parents that i don't waste 1 hour each day on the pc". Yet you do. If you want your pull requests to be merged learn some programming and contribute for real. We are not going to merge useless pull requests.

**Pull request closed without merging**
