### PR TITLE
ENH+BF: fix up of some tests/docs to pass with python2.7, testing on travis, consistent shebanging, 

### PR DESCRIPTION
**Pull request by yarikoptic**
I really loved the idea and the collection so decided to contribute a bit ;)

https://travis-ci.org/yarikoptic/python-patterns/builds/130877280
should eventually reflect current state of things -- either tests pass as is or more things to be done

Please enable travis for your project @faif -- it is easy, just go to http://travis-ci.org, authenticate through github, click toggle for this repository

I have already complained in #143 about necessity to have clear copyright/license statement(s) so this code could e.g. be actually used/redistributed etc.  Ideally the most permissive license (BSD-2 or -3 or MIT) would be the best fit.

Also would be nice to make all code PEP8 compliant. I have added call to flake8 in travis.yml but ignoring its failure atm.  Didn't want to introduce big "stylistic" changes without "go ahead"

### CODE REVIEW

**Comment by yarikoptic** [comment]
ok -- with a small tune up (could not do `|| :` for some reason), now all splendid:  https://travis-ci.org/yarikoptic/python-patterns/builds/130880031

also here is coverage report from https://codecov.io/gh/yarikoptic/python-patterns  (also enable for your repo, and then can add a badge or two to your README etc)

**Comment by fkromer** [comment]
I did not get why lines 81, 61 and 91 in https://codecov.io/gh/yarikoptic/python-patterns/src/ef3dbe3b17b10f9926607f98fa10b1913c61476f/test_hsm.py are not covered...

**Comment by yarikoptic** [comment]
Pushed more fixes and trying to enhance testing by actually running all of the scripts.  It required also fixing 3-tier.py by reverting 69b507b87edd49896ff8877f15010e4f8d30d9e9 -- descriptors must be bound to classes, not to instances, thus that change broke the "pythonish" idea completely.  Could be redone without relying on Python descriptors at the instance level

**Comment by yarikoptic** [comment]
woohoo -- tests pass again (although I have dropped pypy* for now, was getting stuck), and coverage is whooping 93%:  see https://codecov.io/gh/yarikoptic/python-patterns on what to improve.  You can easily get 100% with little effort!

**Comment by yarikoptic** [comment]
On Tue, 17 May 2016, thinwybk wrote:

>    I did not get why lines 81, 61 and 91 in
>    https://codecov.io/gh/yarikoptic/python-patterns/src/ef3dbe3b17b10f9926607f98fa10b1913c61476f/test_hsm.py
>    are not covered...

ain't auto coverage great?! ;)

my guess, is that since it is assertRaises, is that previous lines cause
the exception, so it leaves the context manager scope before executing
them.  Fix should be easy (if legit) to just dedent those  lines out of
the context manager scope ;)

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
On Tue, 17 May 2016, Yaroslav Halchenko wrote:


> On Tue, 17 May 2016, thinwybk wrote:

> >    I did not get why lines 81, 61 and 91 in
> >    https://codecov.io/gh/yarikoptic/python-patterns/src/ef3dbe3b17b10f9926607f98fa10b1913c61476f/test_hsm.py
> >    are not covered...

> ain't auto coverage great?! ;)

> my guess, is that since it is assertRaises, is that previous lines cause
> the exception, so it leaves the context manager scope before executing
> them.  Fix should be easy (if legit) to just dedent those  lines out of
> the context manager scope ;)

ok -- did that for that file... there might be more...
also added some pragma no cover's for points which it is ok to expect no
coverage

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
ok -- `test_hsm` is now at 100% ;)  overall: [codecov](https://codecov.io/gh/yarikoptic/python-patterns)

**Comment by fkromer** [comment]
Thanks a lot :)

**Comment by fkromer** [comment]
Could you merge https://github.com/fkromer/python-patterns/tree/test_proxy (#139) into your fork to make sure these tests are still running ;)

**Comment by yarikoptic** [comment]
On Tue, 17 May 2016, thinwybk wrote:

>    Could you merge https://github.com/fkromer/python-patterns/tree/test_proxy
>    (#139) into your fork to make sure these tests are still running ;)

heh -- only for you and only today...   merged, fixed it up the
test although don't like what I have done and the test logic/duplication
in general.  but better some test than no tests! ;)

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by fkromer** [comment]
Thanks! That's just how it is (right now). :)

**Comment by faif** [comment]
Hi,

Thanks for your contributions. Sorry for not taking any actions yet but I'm ill. I will check everything after recovering. 

Kind regards,
Sakis

**Comment by yarikoptic** [comment]
>    Thanks for your contributions. Sorry for not taking any actions yet but
>    I'm ill. I will check everything after recovering.

sure -- no rush.  Get better!

**Pull request merged**
