### PR TITLE
add: test for proxy.py

### PR DESCRIPTION
**Pull request by fkromer**
#138 brought some tests for the actual proxy.py version on my local machine back to my mind. Runs with Python3.4.1 on Linux.

### CODE REVIEW

**Comment by faif** [comment]
Hi,

Can you please fix the conflicts and resubmit?

**Comment by fkromer** [comment]
Hi, I fix the tests the next days.

**Comment by fkromer** [comment]
Done.

**Comment by faif** [comment]
Hi,

Unfortunately there are still conflicts. Is it possible for you to fix them and send a new pull request?

**Comment by fkromer** [comment]
Oh... I will have a look on it for sure...

**Pull request merged**
