### PR TITLE
[WIP] Create python's package

### PR DESCRIPTION
**Pull request by ar4s**
I would like to create package and testing via tox (with differnt python's
versions).

### CODE REVIEW

**Comment by fkromer** [comment]
What about cleaning up `.gitignore` a bit ("ralph")?

**Comment by pyvim** [comment]
Hmm, but what for? This repo contains examples of code. How it may reuse?

**Comment by ar4s** [comment]
IHMO after my changes you have still fast access to any pattern. I know about reusable this package - is poor, but think about it like a next pattern or good practice. We can easily testing it on Travis via tox with different Python's version.

**Comment by fkromer** [comment]
The package idea is great. As this repo is about design i was just concerned about the package design :)

**Comment by fkromer** [comment]
What do you suggest as overall python version compatibility strategy? I guess it is hard to get one single pattern example which works for all python versions. It is possible for sure but the exemplary character of the patterns could get lost due to the neccessary code overhead which has nothing to do with the patterns. Wrapping python version compatibility stuff into into an imported module (`tests/compat.py`) is a good idea (actualy a pattern itself). However it will not work for every version incompatibility.

[Some compatibility idioms](http://python-future.org/compatible_idioms.html)

**Comment by faif** [comment]
@ar4s I cannot run the tests with your changes. Can you add some instructions about how they are supposed to be executed properly? An example

`python test_state.py`
`...`
`ValueError: Attempted relative import in non-package`

**Comment by ar4s** [comment]
I will describe it in some document like ``README`` or ``CONTRIBUTING``. 

First of all you must install package by following command ``pip install -e '.[dev]'`` (in ``setup.py`` level),
then run simply ``tox`` (by default testing both versions of Python) or ``tox -e py35`` for Python 3.5.
NOTE: Both interpreter must be exists in system.
I recommend create separately environment for development by ``virtualenv`` (https://virtualenv.readthedocs.org/en/latest/)

**Comment by csaez** [comment]
Can we please keep it simple not forcing external dependencies?
I think `unittest` should be enough for anyone wanting to run tests on a particular pattern (or the entire test suite through discovery).

**Comment by ar4s** [comment]
@csaez I agree - ``unittest`` is enough to running test but how test across python versions?

**Comment by csaez** [comment]
@ar4s: I get what you are trying to contribute here (thanks for taking the time!), but I don't think this is the right project as it's not design to be distributed or even solve a particular problem in a generic way, I feel like this PR attempt to solve an inexistent issue and while, sharing is caring, I don't think the additional overhead adds value to the original intent of the project.
If this were a library trying to solve an actual problem in a generic way I would totally back your contribution, but it's not the case, this is about (mostly hardcoded) toy examples showing python implementations of design patterns.

Anyway, I'm just a regular visitor having no say on the direction of the project,
Cheers!

**Comment by faif** [comment]
I agree with @csaez There's no point in introducing unnecessary dependencies for this project. If a pattern can be implemented only in one version then I'm fine with implementing it only in Python 3.

**Pull request closed without merging**
